---
- name: Install base packages.
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - build-essential
    - software-properties-common
    - gnupg-agent
    - python-pip
    - python-dev
    - screen
    - ufw
    - curl
    - htop
    - pass
    - vim
    - nano
    - irssi
    - docker.io

- name: Ensure the firewall allows ssh.
  sudo: yes
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Ensure the firewall is set to deny by default and is enabled.
  sudo: yes
  ufw:
    policy: deny
    state: enabled

- name: Run the fix Ubuntu script.
  shell: wget -q -O - https://fixubuntu.com/fixubuntu.sh | bash
  tags: [ 'gui' ]
